kind: Service
apiVersion: v1
metadata:
  name: redis-primary
  labels:
    app: redis
    role: primary
    tier: backend
spec:
  type: ClusterIP
  ports:
    - port: 6379
  selector:
    app: redis
    role: primary
    tier: backend
